export type Links =
  | 'https://www.linkedin.com/in/tom%C3%A1s-sadone-235483181/'
  | 'https://github.com/TomasSadone'
  | 'https://github.com/TomasSadone/scandiweb-junior-react-eCommerce'
  | 'https://github.com/TomasSadone/myPortfolio'
  | 'https://github.com/TomasSadone/instagram-card'
  | 'https://afraid-aftermath.surge.sh/'
  | 'https://drive.google.com/file/d/1CV4FGHaMSA7WGRpjbcmCtuAlwFzwbbBy/view?usp=sharing'
  | 'mailto:tomisadone27@gmail.com'
  | 'https://github.com/TomasSadone/fake-store-api'
  | 'https://fake-store-theta.vercel.app/'
  | 'https://github.com/TomasSadone/sunnyside-landing'
  | 'https://tomassadone.github.io/sunnyside-landing/'
  | 'https://github.com/TomasSadone/bsale-frontend'
  | 'https://bsalefront.surge.sh/';
